senslarge/senslarge/evaluations/urls.py
from django.conf.urls import include, url

from .views_eval import Root

app_name = 'evaluations'

urlpatterns = [
    url(r'^gestion/', include('senslarge.evaluations.urls_mgmt')),
    url(r'^evaluation/', include('senslarge.evaluations.urls_eval')),
    url(r'^auth/', include('senslarge.evaluations.urls_auth')),
    url(r'^$', Root.as_view(), name='root'),
]

senslarge/senslarge/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^_ht/', include('django_healthchecks.urls')),
    url(r'^', include('senslarge.evaluations.urls')),
]

senslarge/senslarge/evaluations/models.py
import uuid

from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.urls import reverse
from django.core.mail import send_mail
from django.template.loader import render_to_string

from ordered_model.models import OrderedModel


class Formulaire(models.Model):
    POND = 'PONDERATION'
    SELECT = 'SELECTION'
    SELECT_VAL = 'SELECTION_VALORISATION'
    TYPES = [
        (POND, 'Ponderation'),
        (SELECT, 'Selection'),
        (SELECT_VAL, 'Selection and Valorisation')
    ]
    titre = models.CharField(max_length=200, verbose_name="Titre")
    introduction = models.TextField(verbose_name="Introduction")
    type_form = models.CharField(
        choices=TYPES, max_length=26, verbose_name="Type"
    )
    nb_points = models.IntegerField(
        default=0,
        verbose_name="Nombre de points",
        help_text="À répartir entre les choix",
    )

    BARRE = 'radar'
    SELECT = 'barres'
    GRAPH = [
        (BARRE, 'radar'),
        (SELECT, 'barres')
    ]
    typegraphe = models.CharField(
        choices=GRAPH, max_length=7, verbose_name="Graphique"
    )

    def __str__(self):
        return self.titre


class Question(OrderedModel):
    question_text = models.TextField(verbose_name="Texte")
    formulaire = models.ForeignKey(
        'Formulaire',
        related_name="questions",
        on_delete=models.CASCADE,
        verbose_name="Formulaire",
    )

    order_with_respect_to = 'formulaire'

    class Meta:
        ordering = ('formulaire', 'order')

    def __str__(self):
        return self.question_text


class Choice(OrderedModel):
    choice_text = models.TextField(
        blank=True, verbose_name="Texte"
    )
    question = models.ForeignKey(
        'Question',
        related_name="choices",
        on_delete=models.CASCADE,
        verbose_name="Question",
    )
    categorie = models.ForeignKey(
        'Categorie',
        related_name="choixcategories",
        null=True,
        on_delete=models.CASCADE,
        verbose_name="Catégorie",
    )
    VALPLUS0 = '0'
    VALPLUS1 = '+1'
    VALPLUS2 = '+2'
    VALPLUS3 = '+3'
    VALMOINS1 = '-1'
    VALMOINS2 = '-2'
    VALMOINS3 = '-3'
    VAL = [
        (VALPLUS0, '0'),
        (VALPLUS1, '+1'),
        (VALPLUS2, '+2'),
        (VALPLUS3, '+3'),
        (VALMOINS1, '-1'),
        (VALMOINS2, '-2'),
        (VALMOINS3, '-3')
    ]
    valorisation = models.CharField(
        default=0, choices=VAL, max_length=2, verbose_name="Valorisation"
    )

    order_with_respect_to = 'question'

    class Meta:
        ordering = ('question', 'order')


class Categorie(models.Model):
    categorie_text = models.TextField(
        max_length=200, blank=True, verbose_name="Texte"
    )
    formulaire = models.ForeignKey(
        'Formulaire',
        related_name="categories",
        on_delete=models.CASCADE,
        verbose_name="Formulaire",
    )

    def __str__(self):
        return self.categorie_text


class ChoiceUtilisateur(models.Model):
    reference_user = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )
    reference_choice = models.ForeignKey(
        'Choice',
        related_name="choiceusers",
        on_delete=models.CASCADE
    )
    valeur_entier = models.IntegerField(default=0)


class TicketFormulaire(models.Model):
    formul = models.ManyToManyField(
        'Formulaire',
        related_name="tickets"
    )
    users_lien = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name="formulaires",
    )
    token = models.UUIDField(
        default=uuid.uuid4, editable=False
    )

    def send_to_user(self, request):
        url_formulaire = reverse(
            'evaluations:introduction_formulaire', kwargs={
                'token': str(self.token)
            }
        )
        url = request.build_absolute_uri(url_formulaire)

        txt_message = render_to_string(
            'evaluations/emails/ticket_utilisateur/body.txt',
            {'object': self, 'url': url}
        )
        html_message = render_to_string(
            'evaluations/emails/ticket_utilisateur/body.html',
            {'object': self, 'url': url}
        )
        send_mail(
            'Votre évaluation Sens Large',
            txt_message,
            settings.DEFAULT_FROM_EMAIL,
            [self.users_lien.email],
            html_message=html_message
        )


class FormUser:
    def __init__(self, form, user):
        self.form = form
        self.user = user

    def header(self):
        return self.form.categories.order_by('pk').values_list(
            'categorie_text', flat=True
        )

    def rows(self):
        if self.form.type_form == self.form.SELECT_VAL:
            yield from self.rows_select_val()
            return
        for question in self.form.questions.all():
            choix = (
                ChoiceUtilisateur.objects.filter(
                    reference_user=self.user,
                    reference_choice__question=question
                )
                .order_by('reference_choice__categorie__pk')
            )
            yield question, choix

    def rows_select_val(self):
        for question in self.form.questions.all():
            choices = []
            for choice in question.choices.order_by('categorie__pk'):
                choices.append((choice, ChoiceUtilisateur.objects.filter(
                    reference_user=self.user,
                    reference_choice=choice
                ).exists()))
            print(question, choices)
            yield question, choices

    def footer(self):
        row = []
        if self.form.type_form == self.form.SELECT_VAL:
            return self.footer_select_val()

        for question, choices in self.rows():
            row_started = bool(row)
            for i, choice in enumerate(choices):
                if not row_started:
                    row.append(choice.valeur_entier)
                else:
                    row[i] += choice.valeur_entier
        return row

    def footer_select_val(self):
        row = []
        for question, choices in self.rows():
            row_started = bool(row)
            for i, choice in enumerate(choices):
                if not row_started:
                    row.append(choice[1] and 1 or 0)
                else:
                    row[i] += choice[1] and 1 or 0
        return row

    def footer_select_val_sum(self):
        row = [0 for c in self.form.categories.all()]
        for question in self.form.questions.all():
            qs = question.choices.order_by('categorie__pk')
            for i, choice in enumerate(qs):
                user_choice = ChoiceUtilisateur.objects.filter(
                    reference_user=self.user,
                    reference_choice=choice
                ).first()
                if user_choice:
                    if choice.valorisation[0] == '+':
                        row[i] += int(choice.valorisation[1])
                    else:
                        row[i] += int(choice.valorisation)
        return row

    def performance(self):
        return sum(self.footer_select_val_sum())

senslarge/senslarge/evaluations/forms.py
from django import forms
from .models import Formulaire, Choice, Categorie
from django.contrib.auth.models import User


class ChoiceForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        my_formulaire = kwargs.pop('my_formulaire')
        reponse = super().__init__(*args, **kwargs)
        self.fields['categorie'].queryset = Categorie.objects.filter(
            formulaire=my_formulaire
        )
        return reponse

    class Meta:
        model = Choice
        fields = ['choice_text', 'categorie', 'valorisation']


class ChoiceFormEdit(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        formulaire = kwargs.pop('formulaire')

        super().__init__(*args, **kwargs)

        self.fields['categorie'].queryset = Categorie.objects.filter(
            formulaire=formulaire
        )

    class Meta:
        model = Choice
        fields = ['choice_text', 'categorie', 'valorisation']


class UserForm(forms.ModelForm):
    formulaires = forms.ModelMultipleChoiceField(
        required=False,
        widget=forms.CheckboxSelectMultiple,
        queryset=Formulaire.objects.all(),
        label='Formulaires associés',
    )

    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'email',
            'formulaires',
        ]

    def clean_email(self):
        data = self.cleaned_data['email']
        if User.objects.filter(email=data).exists():
            raise forms.ValidationError(
                "Cette adresse mail est déjà utilisée par un autre utilisateur"
            )
        return data


class UserChoiceForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.my_formulaire = kwargs.pop('my_formulaire')
        reponse = super().__init__(*args, **kwargs)
        return reponse

    def clean(self):
        cleaned_data = super().clean()
        if self.my_formulaire.nb_points != sum(cleaned_data.values()):
            raise forms.ValidationError(
                "La somme totale des points doit être égale à {}.".format(
                    self.my_formulaire.nb_points
                )
            )
        return cleaned_data

senslarge/senslarge/evaluations/templates/evaluations/creation_categorie.html
{% extends 'evaluations/base.html' %}

{% load bootstrap3 %}

{% block content %}
<h1>Ajout de catégorie</h1>

<p><a class="btn btn-default" href="{% url "evaluations:formulaire" pk=formulaire.pk %}">Retour</a></p>

<form method="POST" class="form-horizontal">
  {% csrf_token %}

  <div class="form-group">
    <label class="col-md-3 control-label" for="id_question">Formulaire</label>
    <div class="col-md-9"><p class="form-control-static">{{formulaire.titre}}</p></div>
  </div>

  {% bootstrap_form form layout='horizontal' %}
  {% bootstrap_button "Créer" button_type="submit" button_class="btn btn-success btn-lg pull-right" %}
</form>
{% endblock %}

senslarge/senslarge/evaluations/templates/evaluations/creation_choix.html
 {% extends 'evaluations/base.html' %} {% load bootstrap3 %}

 {% block content %}

<h1>Ajout de choix</h1>

<p><a class="btn btn-default" href="{% url "evaluations:formulaire" pk=question.formulaire.pk %}">Retour</a></p>

<form method="POST" class="form-horizontal">
  {% csrf_token %}

  <div class="form-group">
    <label class="col-md-3 control-label" for="id_question">Question</label>
    <div class="col-md-9"><p class="form-control-static">{{question.question_text}}</p></div>
  </div>

  {% bootstrap_form form layout='horizontal' %}
  {% bootstrap_button "Créer" button_type="submit" button_class="btn btn-success btn-lg pull-right" %}
</form>
{% endblock %}

senslarge/senslarge/evaluations/templates/evaluations/creation_question.html
{% extends 'evaluations/base.html' %} {% load bootstrap3 %}

{% block content %}

<h1>Création de question</h1>

<p><a class="btn btn-default" href="{% url "evaluations:formulaire" pk=formulaire.pk %}">Retour</a></p>

<form method="POST" class="form-horizontal">
  {% csrf_token %}

  <div class="form-group">
    <label class="col-md-3 control-label" for="id_question">Formulaire</label>
    <div class="col-md-9"><p class="form-control-static">{{formulaire.titre}}</p></div>
  </div>

  {% bootstrap_form form layout='horizontal' %}
  {% bootstrap_button "Créer" button_type="submit" button_class="btn btn-success btn-lg pull-right" %}
</form>
{% endblock %}

senslarge/senslarge/evaluations/templates/evaluations/detail_formulaire.html
{% extends 'evaluations/base.html' %}

{% load bootstrap3 %}

{% block content %}

<h1>{{ formulaire.titre}}</h1>

<p>
    <a class="btn btn-default" href="{% url "evaluations:liste_formulaire" %}">Retour</a>
    <a class="btn btn-primary" href="{% url "evaluations:edition_formulaire" formulaire.pk %}">Modifier</a>
</p>

<h2>Formulaire</h2>

<form class="form-horizontal">
  <div class="form-group">
    <label class="col-sm-2 control-label">Introduction</label>
    <div class="col-sm-10">
      <p class="form-control-static">{{ formulaire.introduction }}</p>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">Type</label>
    <div class="col-sm-10">
      <p class="form-control-static">{{ formulaire.get_type_form_display }}</p>
    </div>
  </div>
  {% if formulaire.type_form == formulaire.POND %}
  <div class="form-group">
    <label class="col-sm-2 control-label">Nombre de points</label>
    <div class="col-sm-10">
      <p class="form-control-static">{{ formulaire.nb_points }}</p>
    </div>
  </div>
  {% endif %}
  <div class="form-group">
    <label class="col-sm-2 control-label">Graphique</label>
    <div class="col-sm-10">
      <p class="form-control-static">{{ formulaire.get_typegraphe_display }}</p>
    </div>
  </div>
</form>

<h2>Catégories</h2>
<p>
  <a href="{% url 'evaluations:creation_categorie' formulaire_pk=formulaire.pk %}"class="btn btn-success">Créer</a>
</p>

<table class="table table-hover">
{% for category in formulaire.categories.all %}
<tr>
  <td>{{ category.categorie_text }}</td>
  <td><a class="btn btn-default pull-right" href="{% url 'evaluations:edition_categorie' formulaire_pk=formulaire.pk pk=category.pk %}">Modifier</a></td>
</tr>
{% endfor %}
</table>

<h2>Questions</h2>

<p>
  <a href="{% url 'evaluations:creation_question' formulaire_pk=formulaire.pk %}" class="btn btn-success">Créer</a>
</p>

{% for question in formulaire.questions.all %}
  <h3>{{ question.question_text}} <a class="btn btn-primary btn-sm" href="{% url 'evaluations:edition_question' formulaire_pk=formulaire.pk pk=question.pk %}">Modifier</a></h3>

<table class="table table-hover">
{% for choice in question.choices.all %}
<tr>
    <td>{{ choice.choice_text}}</td>
    <td class="text-center"><span class="label label-info">{{ choice.categorie.categorie_text}}</span></td>
    <td><a href="{% url 'evaluations:edition_choice' formulaire_pk=formulaire.pk question_pk=question.pk choice_pk=choice.pk %}" class="btn btn-default btn-sm pull-right">Modifier</a></td>
</tr>
{% endfor %}
<tr>
  <td colspan="3"><a href="{% url 'evaluations:creation_choice' formulaire_pk=formulaire.pk question_pk=question.pk %}" class="btn btn-success btn-sm">Ajouter un choix</a></td>
</tr>
</table>
{% endfor %}

{% endblock %}

senslarge/senslarge/evaluations/templates/evaluations/detail_repondant.html
{% extends 'evaluations/base.html' %}

{% load bootstrap3 %}
{% load static %}
{% load fontawesome %}

{% block content %}
<style>
@media print{
  .h1, h1 {
    font-size: 18px;
  }
  .h2, h2 {
    font-size: 15px;
  }
  .h3, h3 {
    font-size: 12px;
  }
  .h1, .h2, .h3, h1, h2, h3 {
      margin-top: 10px;
      margin-bottom: 5px;
  }
  body {
    font-size: 10px;
  }
  ol, ul {
    margin-top: 0;
    margin-bottom: 5px;
  }
}
</style>


<h1>
  {{formulaire.titre}} : {{utilisateur.username}}
  <a class="btn btn-default pull-right hidden-print" href="{% url 'evaluations:creation_pdf' formulaire_pk=formulaire.pk user_pk=utilisateur.pk %}">
    PDF
  </a>
</h1>

{% if formulaire.titre != "Style de comportement" %}
<h2>Détail des réponses</h2>

{% for question in formulaire.questions.all %}
<h3> {{question.question_text}}</h3>
      <ul>
  {% for choice in question.choices.all %}
    {% for choice_user in choice.choiceusers.all %}
        {% if formulaire.type_form == formulaire.POND %}
          <li>
            {{choice_user.reference_choice.choice_text}}&nbsp;: <span>{{choice_user.valeur_entier}}</span>
          </li>
        {% else %}
          {% for choice in choice_user.reference_choice.question.choices.all %}
            <li>
            {% if choice == choice_user.reference_choice %}
                {% fontawesome_icon 'check-square-o' %}
            {% else %}
                {% fontawesome_icon 'square-o' %}
            {% endif %}
            {{choice.choice_text}}
            </li>
          {% endfor %}
        {% endif %}
    {% endfor %}
  {% endfor %}
      </ul>
{% endfor %}

<h2>Résumé par catégorie</h2>
<table class="table table-border">
<thead>
<tr>
  <th></th>
  {% for categorie in form_user.header %}
  <th class="text-center">{{ categorie }}</th>
  {% endfor %}
</tr>
</thead>
<tbody>
{% for question, choices in form_user.rows %}
<tr>
  <td>{{ question.question_text }}</td>
  {% for choice in choices %}
  <td class="text-center">
    {% if formulaire.type_form == formulaire.POND %}
      {{ choice.valeur_entier}}
    {% else %}
      {% if choice.1 %}
      {% fontawesome_icon 'check-square-o' %}
      {% else %}
      {% fontawesome_icon 'square-o' %}
      {% endif %}
      <br/>
      {{ choice.0.valorisation }}
    {% endif %}
  </td>
  {% endfor %}
</tr>
{% endfor %}
<tr>
  <th class="text-right">{% if formulaire.type_form != formulaire.POND %}Nombre{% endif %}</th>
  {% for cell in form_user.footer %}
  <th class="text-center">{{ cell }}</th>
  {% endfor %}
</tr>
{% if formulaire.type_form != formulaire.POND %}
<tr>
  <th class="text-right">Somme</th>
  {% for cell in form_user.footer_select_val_sum %}
  <th class="text-center">{{ cell }}</th>
  {% endfor %}
</tr>
<tr>
  <th class="text-right">Performance</th>
  <th colspan="4" class="text-center">{{ form_user.performance }} / 36</th>
</tr>
{% endif %}
</tbody>
</table>
{% else %}
<h2>Résumé par catégorie</h2>
<table class="table table-border">
<thead>
<tr>
  {% for categorie in form_user.header %}
  <th></th>
  <th class="text-center">{{ categorie }}</th>
  {% endfor %}
</tr>
</thead>
<tbody>
{% for question, choices in form_user.rows %}
<tr>
  {% for choice in choices %}
  <td class="text-right">
    {{choice.reference_choice.choice_text}}
  </td>
  <td class="text-center">
    {{ choice.valeur_entier}}
  </td>
  {% endfor %}
</tr>
{% endfor %}
<tr>
  {% for cell in form_user.footer %}
  <th></th>
  <th class="text-center">{{ cell }}</th>
  {% endfor %}
</tr>
</tbody>
</table>
{% endif %}

<div class="graph">
  {% if formulaire.titre == "Style de comportement" %}
    <h2>Interprétation graphique des choix</h2>
    <div class="legend text-center square" >
        <div class="line">
          <div class="category">
            D (dominant) <br /> Centré resultat<br>{{categorie.2}}
          </div>
          <div class="category">
            I (influent)<br />Entraineur de groupe<br>{{categorie.3}}
          </div>
        </div>
        <div class="line">
          <div class="category">
            {{categorie.0}}<br />C(consciencieux) <br />Analytique
          </div>
          <div class="category">
            {{categorie.1}}<br />S(stable)<br />Relationnel individuel
          </div>
        </div>
    </div>
      <object class="pygal square" type="image/svg+xml" data="{% url 'evaluations:graphe' formulaire_pk=formulaire.pk user_pk=utilisateur.pk %}" ></object>

  {% elif formulaire.titre == "Approche systemique" %}

  <h2>Interprétation graphique des choix</h2>
    <object class="pygal" type="image/svg+xml" data="{% url 'evaluations:graphe_s' formulaire_pk=formulaire.pk user_pk=utilisateur.pk %}" ></object>

  {% elif formulaire.titre == "Approche gagnant-gagnant" %}

  <h2>Interprétation graphique des choix</h2>

    <div class="legend text-center square">
        <div class="line">
          <div class="category">
            -+ <br/> P/G Soumission
          </div>
          <div class="category">
            ++ <br/> G/G Coopération
          </div>
        </div>
        <div class="line">
          <div class="category">
            -- <br/> P/P Démission
          </div>
          <div class="category">
            +- <br/> G/P Domination
          </div>
        </div>
    </div>
      <object class="pygal square" type="image/svg+xml" data="{% url 'evaluations:graphe_g' user_pk=utilisateur.pk formulaire_pk=formulaire.pk %}" ></object>
  {% endif %}
</div>

<style>
.graph {
  width:532px;
  background:white;
  overflow-wrap:normal;
  height: 403px;
  position: relative;
}
.legend{
  width:532px;
  height: 403px;
  overflow-wrap:normal;
  position: absolute;
  z-index: 1;
}
.pygal{
  width:532px;
  height: 403px;
}

.square{
  height: 532px;
}

.line:first-of-type{
  position: absolute;
  top: 0;
  width: 100%;
}

.line:last-of-type{
  position: absolute;
  bottom: 0;
  width: 100%;
}

.category{
  width: 50%;
  float: left;
}
</style>
{% endblock %}

senslarge/senslarge/evaluations/templates/evaluations/edition_categorie.html
{% extends 'evaluations/base.html' %}

{% load bootstrap3 %}

{% block content %}
<h1>Modification de catégorie</h1>

<p><a class="btn btn-default" href="{% url "evaluations:formulaire" pk=object.formulaire.pk %}">Retour</a></p>

<form method="POST" class="form-horizontal">
  {% csrf_token %}
  {% bootstrap_form form layout='horizontal' %}
  {% bootstrap_button "Modifier" button_type="submit" button_class="btn btn-success btn-lg pull-right" %}
</form>
{% endblock %}

senslarge/senslarge/evaluations/templates/evaluations/edition_choix.html
 {% extends 'evaluations/base.html' %}

{% load bootstrap3 %}

 {% block content %}

<h1>Modification de choix</h1>

<p><a class="btn btn-default" href="{% url "evaluations:formulaire" pk=object.question.formulaire.pk %}">Retour</a></p>

<form method="POST" class="form-horizontal">
  {% csrf_token %}
  {% bootstrap_form form layout='horizontal' %}
  {% bootstrap_button "Modifier" button_type="submit" button_class="btn btn-lg btn-success pull-right" %}
</form>
{% endblock %}

senslarge/senslarge/evaluations/templates/evaluations/edition_formulaire.html
 {% extends 'evaluations/base.html' %}

{% load bootstrap3 %}

{% block content %}
<h1>Modification de formulaire</h1>

<p><a class="btn btn-default" href="{% url "evaluations:formulaire" pk=object.pk %}">Retour</a></p>

<form method="POST" class="form-horizontal">
  {% csrf_token %}
  {% bootstrap_form form layout='horizontal' %}
  {% bootstrap_button "Enregistrer" button_type="submit" button_class="btn btn-success btn-lg pull-right" %}
</form>
{% endblock %}

senslarge/senslarge/evaluations/templates/evaluations/edition_question.html
 {% extends 'evaluations/base.html' %}

{% load bootstrap3 %}

{% block content %}

<h1>Modification de choix</h1>

<p><a class="btn btn-default" href="{% url "evaluations:formulaire" pk=object.formulaire.pk %}">Retour</a></p>

<form method="POST" class="form-horizontal">
  {% csrf_token %}
  {% bootstrap_form form layout='horizontal' %}
  {% bootstrap_button "Modifier" button_type="submit" button_class="btn btn-lg btn-success pull-right" %}
</form>
{% endblock %}

senslarge/senslarge/evaluations/templates/evaluations/introductionformulaire.html
 {% extends 'evaluations/base.html' %}

{% load bootstrap3 %}
{% load static %}

{% block content %}

<div class="row col-md-6 col-md-offset-3 text-center">

<img src="{% static 'logo.png' %}" />

<h3>
    Evaluation Sens Large
</h3>

{% if object_list.count == 0%}
<p>
    Vous avez rempli tous les formulaires demandés
</p>

{% else %}

<p>
  Ci-dessous, {% if object_list.count == 1%}le formulaire{% else %}les formulaires{% endif %} à remplir.<br />
  Vous êtes libre de commencer par celui que vous voulez :
</p>

{% for formulaire in object_list %}
  <p class="clearfix">{{ formulaire.titre }}
    <a href="{% url 'evaluations:repondre_question' formulaire_pk=formulaire.pk question_pk=formulaire.questions.first.pk %}" class="btn btn-primary pull-right">Répondre</a>
  </p>
{% endfor %}
{% endif %}
</div>

{% endblock %}

senslarge/senslarge/evaluations/templates/evaluations/listerepondant.html
{% extends 'evaluations/base.html' %}

{% load bootstrap3 %}

{% block content %}
<h1> Liste des répondants</h1>
<p>
  <a href="{% url 'evaluations:creation_repondant' %}" class="btn btn-success">Ajouter un répondant</a>
</p>

<table class="table table-hover">
{% for user in object_list %}
<tr>
  <td>
  {% if user.username %}
    {{user.username}}
  {% else%}
    {{user.first_name}} {{user.last_name}}
  {% endif %}
  </td>
  <td>
     {% for formul in user.formulaires.formul.all %}
       <a href="{% url 'evaluations:repondant' formulaire_pk=formul.pk user_pk=user.pk %}">
         {{ formul.titre }}
       </a>
     {% endfor %}
  </td>
  <td>
    <a  class="btn btn-primary" href="{% url 'evaluations:edition_repondant' pk=user.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
  </td>
</tr>
{% endfor %}
</table>
{% endblock %}

senslarge/senslarge/evaluations/templates/evaluations/login.html
{% extends 'evaluations/base.html' %}

{% load bootstrap3 %}
{% load static %}

{% block content %}

<div class="row col-md-8 col-md-offset-2">
<p class="text-center">
  <img src="{% static "logo.png" %}" />
</p>
<form method="POST" class="form-horizontal">{% csrf_token %}
 {% bootstrap_form form layout='horizontal' %}
<p class="text-center"><a href="{% url 'evaluations:password_reset' %}">Réinitialisation du mot de passe</a></p>
 {% bootstrap_button "Se connecter" button_type="submit" button_class="btn btn-success btn-lg pull-right" %}
</form>
</div>

{% endblock %}

senslarge/senslarge/evaluations/templates/evaluations/password_reset_complete.html
{% extends 'evaluations/base.html' %}

{% load bootstrap3 %}
{% load i18n %}

{% block content %}

<div class="row col-md-8 col-md-offset-2">

<h1>Mise à jour du mot de passe terminée</h1>

<p>Votre mot de passe a été défini. Vous pouvez maintenant vous authentifier.</p>

<p><a class="btn btn-success btn-lg pull-right" href="{{ login_url }}">Se connecter</a></p>

</div>

{% endblock %}

senslarge/senslarge/evaluations/templates/evaluations/password_reset_confirm.html
{% extends 'evaluations/base.html' %}

{% load bootstrap3 %}
{% load i18n %}

{% block content %}

<div class="row col-md-8 col-md-offset-2">

<h1>Saisissez un nouveau mot de passe</h1>

{% if validlink %}

<p>Saisissez deux fois votre nouveau mot de passe afin de vérifier qu'il est correctement saisi.</p>

<form method="POST" class="form-horizontal">
  {% csrf_token %}
  {% bootstrap_form form layout='horizontal' %}
  {% bootstrap_button "Modifier mon mot de passe" button_type="submit" button_class="btn btn-success btn-lg pull-right" %}
</form>

{% else %}

<p>Le lien de mise à jour du mot de passe n'était pas valide, probablement en raison de sa précédente utilisation. Veuillez renouveler votre demande de mise à jour de mot de passe.</p>

{% endif %}

</div>

{% endblock %}